org: ianfs
service: foodiary-api

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}

custom:
  userPoolName: "${self:service}-${self:provider.stage}-UserPool"
  userPoolClientName: "${self:service}-${self:provider.stage}-UserPoolClient"

package:
  individually: true

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./sls/functions/auth.yml)}

resources:
  - ${file(./sls/resources/UserPool.yml)}
