org: ianfs
service: foodiary-api

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs22.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  environment: ${file(./sls/config/env.yml)}
  iam:
    role: ${file(./sls/config/role.yml)}
custom:
  cognito:
    userPoolName: "${self:service}-${self:provider.stage}-UserPool"
    userPoolClientName: "${self:service}-${self:provider.stage}-UserPoolClient"

package:
  individually: true

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  - ${file(./sls/functions/auth.yml)}

resources:
  - ${file(./sls/resources/UserPool.yml)}
  - ${file(./sls/resources/MainTable.yml)}
