updateProfile:
    handler: src/main/functions/profiles/updateProfile.handler
    events:
      - httpApi:
          path: /profile
          method: PUT
          authorizer:
            name: CognitoAuthorizer
