export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",

  // HTTP
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
}
